local tasks = { { level = "1", tasknummer = "1", taskText = "??pri*.?*", answer1 = "napri.q", answer2 = "pripri.txt", answer3 = "privet.doc", answer4 = "3priveta.c", correct = "1" },
{ level = "1", tasknummer = "2", taskText = "?fil?*.w", answer1 = " refiled.wmf", answer2 = "fil.w", answer3 = "ffilpage.w", answer4 = "nadfil.w", correct = "3" },
{ level = "1", tasknummer = "3", taskText = "sys??.*", answer1 = "syste.ma", answer2 = "sys.", answer3 = "system.sys", answer4 = "syst.ema", correct = "1" },
{ level = "1", tasknummer = "4", taskText = "?еll*.??", answer1 = "yell.ow", answer2 = "bell.с", answer3 = "yellow.color", answer4 = "2ell.12", correct = "4" },
{ level = "1", tasknummer = "5", taskText = "*fi*m.?*i", answer1 = "fimi.i", answer2 = "film.avi", answer3 = "fimi.ip", answer4 = "film.inf", correct = "2" },
{ level = "1", tasknummer = "6", taskText = "?m?l.d*c", answer1 = "mmmml.dc", answer2 = "my_myl.doc", answer3 = "ymyl.doc", answer4 = "mymyl.doc", correct = "3" },
{ level = "1", tasknummer = "7", taskText = "?*ris*.*p", answer1 = "tetris.op", answer2 = "ris.chp", answer3 = "ris.sp", answer4 = "krisis.aw", correct = "1" },
{ level = "1", tasknummer = "8", taskText = "?mas*.p*", answer1 = "massiv.pas", answer2 = "mmassiv.p", answer3 = "mmassiv.cpp", answer4 = "mas.p", correct = "2" },
{ level = "1", tasknummer = "9", taskText = "*fi??.b*", answer1 = "file.ebb", answer2 = "wi_fi.bat", answer3 = "file.fib", answer4 = "file.bat", correct = "4" },
{ level = "2", tasknummer = "1", taskText = "??рri*.?*", answer1 = "caprika.wow", answer2 = "weprik.cpp", answer3 = "otopri.e", answer4 = "reprint.be", correct = "3" },
{ level = "2", tasknummer = "2", taskText = "?fil?*.w", answer1 = "files.w", answer2 = "afile.w", answer3 = "2files.w", answer4 = "1filled.w", correct = "1" },
{ level = "2", tasknummer = "3", taskText = "sys??.*", answer1 = "syste.m", answer2 = "sys23.exe", answer3 = "system.dll", answer4 = "syszx.problem", correct = "3" },
{ level = "2", tasknummer = "4", taskText = "?ell*.??", answer1 = "yell.ow", answer2 = "fellow.га", answer3 = "tell_me.tu", answer4 = "bell.lab", correct = "4" },
{ level = "2", tasknummer = "5", taskText = "?*di.t?*", answer1 = "poydi.t", answer2 = "pogudi.tanx", answer3 = "3di.t9", answer4 = "melodi.theme", correct = "1" },
{ level = "2", tasknummer = "6", taskText = "?ell*.??", answer1 = "yell.ow", answer2 = "fellow.га", answer3 = "tel!__me.tu", answer4 = "bell.la", correct = "3" },
{ level = "2", tasknummer = "7", taskText = "??pr*.?*", answer1 = "caprika.wow", answer2 = "weprik.cpp", answer3 = "otopri.e", answer4 = "reprint.be", correct = "3" },
{ level = "2", tasknummer = "8", taskText = "?fil?*.w", answer1 = "filcs.w", answer2 = "afile.w", answer3 = "2files.w", answer4 = "lfilled.w", correct = "1" },
{ level = "2", tasknummer = "9", taskText = "sys??.*", answer1 = "syste.m", answer2 = "sys23.exe", answer3 = "system.dll", answer4 = "syszx.problem", correct = "3" }}
return tasks
